security:
    encoders:
        AppBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12

    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            provider: database_users
            form_login:
                check_path: /login_check
                login_path: /login

            logout:
                path: /logout
                target: homepage
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
